
INSERT INTO "Collections" VALUES ('GetInTouchPage','Get In touch Page','Get In touch ',0,'{"type":"object","properties":{"Title":{"type":"string","title":"Title"},"Description":{"type":"string","title":"Description"},"ContactInfo":{"type":"array","title":"Contact Info","items":{"type":"object","title":"Contact Info","properties":{"Address":{"type":"object","title":"Address","properties":{"Icon":{"type":"string","title":"Icon"},"Title":{"type":"string","title":"Title"}},"required":["Icon","Title"]}},"required":["Address"]}}},"required":["Title","Description","ContactInfo"]}','{"Title":{},"Description":{},"ContactInfo":{"items":{"Address":{"Icon":{},"Title":{}}}}}','[{"name":"Title","type":"string","title":"Title","isRequired":true,"isCollapsed":false},{"name":"Description","type":"string","title":"Description","isRequired":true,"isCollapsed":false},{"name":"ContactInfo","type":"array","title":"Contact Info","isRequired":true,"isCollapsed":false,"children":[{"name":"Address","type":"json","title":"Address","isRequired":true,"isCollapsed":false,"children":[{"name":"Icon","type":"string","title":"Icon","isRequired":true,"isCollapsed":false},{"name":"Title","type":"string","title":"Title","isRequired":true,"isCollapsed":false}]}]}]',1718075985571,1718157911552);


INSERT INTO "Collections" VALUES ('PublicMenu','Public Menu','Public Menu',0,'{"type":"object","properties":{"PublicMenu":{"type":"array","title":"Public Menu","items":{"type":"object","title":"Public Menu","properties":{"Text":{"type":"string","title":"Text"},"Icon":{"type":"string","title":"Icon"},"Link":{"type":"string","title":"Link"},"Level":{"type":"number","title":"Level"}},"required":[]}}},"required":[]}','{"PublicMenu":{"items":{"Text":{},"Icon":{},"Link":{},"Level":{}}}}','[{"name":"PublicMenu","type":"array","title":"Public Menu","isRequired":false,"isCollapsed":false,"children":[{"name":"Text","type":"string","title":"Text","isRequired":false,"isCollapsed":false},{"name":"Icon","type":"string","title":"Icon","isRequired":false,"isCollapsed":false},{"name":"Link","type":"string","title":"Link","isRequired":false,"isCollapsed":false},{"name":"Level","type":"number","title":"Level","isRequired":false,"isCollapsed":false}]}]',1718085159895,1718161530717);



INSERT INTO "Collections" VALUES ('UserMenu','User Menu','User Menu',0,'{"type":"object","properties":{"Cart":{"type":"boolean","title":"Cart"},"Notification":{"type":"boolean","title":"Notification"},"Profile":{"type":"boolean","title":"Profile"},"Promo":{"type":"array","title":"Promo","items":{"type":"object","title":"Promo","properties":{"Text":{"type":"string","title":"Text"},"Link":{"type":"string","title":"Link"},"Target":{"type":"string","title":"Target"}},"required":[]}}},"required":[]}','{"Cart":{},"Notification":{},"Profile":{},"Promo":{"items":{"Text":{},"Link":{},"Target":{}}}}','[{"name":"Cart","type":"boolean","title":"Cart","isRequired":false,"isCollapsed":false},{"name":"Notification","type":"boolean","title":"Notification","isRequired":false,"isCollapsed":false},{"name":"Profile","type":"boolean","title":"Profile","isRequired":false,"isCollapsed":false},{"name":"Promo","type":"array","title":"Promo","isRequired":false,"isCollapsed":false,"children":[{"name":"Text","type":"string","title":"Text","isRequired":false,"isCollapsed":false},{"name":"Link","type":"string","title":"Link","isRequired":false,"isCollapsed":false},{"name":"Target","type":"string","title":"Target","isRequired":false,"isCollapsed":false}]}]',1718172134876,NULL);
